### ISSUE TITLE
Cannot read property 'length' of undefined - protobufjs

### ISSUE THREAD

**Issue by Cdik** [googleapis/nodejs-video-intelligence#297]
#### Environment details

  - OS: Mac OS
  - Node.js version: 11.5.0
  - npm version: 6.10.2
  - `@google-cloud/video-intelligence` version: 2.3.0

Error linked to [this](https://github.com/googleapis/nodejs-kms/issues/207#issue-494565663) and [this](https://github.com/googleapis/nodejs-pubsub/issues/739#issue-492867153) and probably some others.

@callmehiphop @alexander-fenster 

Looks like @Draiken found the issue --> [here](https://github.com/googleapis/nodejs-pubsub/issues/739#issuecomment-531196328)

Could you please provide an update. Thanks. For now I have just downgraded to v2.2.2

Error thrown:
```
TypeError: Cannot read property 'length' of undefined
    at Root.load (/srv/node_modules/protobufjs/src/root.js:192:44)
    at Root.loadSync (/srv/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (/srv/node_modules/@grpc/proto-loader/build/src/index.js:230:27)
    at GrpcClient.loadFromProto (/srv/node_modules/google-gax/build/src/grpc.js:118:44)
    at GrpcClient.loadProto (/srv/node_modules/google-gax/build/src/grpc.js:145:21)
    at new VideoIntelligenceServiceClient (/srv/node_modules/@google-cloud/video-intelligence/src/v1/video_intelligence_service_client.js:120:28)
    at Object.<anonymous> (/srv/utilities/safetyChecks.js:9:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.exports.originalsProcess (/srv/upload/originalsProcess.js:37:24)
    at Object.exports.process (/srv/upload/thumbnailGeneration.js:47:31)
    at Object.exports.process (/srv/upload/thumbnailCreation.js:15:30)
    at exports.thumbnailProcess.functions.storage.object.onFinalize (/srv/index.js:163:30)
    at cloudFunction (/srv/node_modules/firebase-functions/lib/cloud-functions.js:131:23)
    at /worker/worker.js:825:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by alexander-fenster** [comment]
Hi @Cdik, 

If you make sure you reinstall the latest versions of dependencies, the error will go away (remove your lock file `package-lock.json` and `node_modules` and re-run `npm install`). 

I'll also release this library with updated dependencies to make sure it works for all users (doing it right now).

**Comment by Cdik** [comment]
@alexander-fenster 

I tried both on separate directories: 
- clean npm install -> fixed the issue.
and 
- update 2.4.0 -> fixed the issue.

Thanks :)

**Comment by bcoe** [comment]
Awesome, I'm glad you're unblocked @Cdik.
