### ISSUE TITLE
Unchanged samples suddenly failing on master

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-video-intelligence#420]
So this seems bad:
https://github.com/googleapis/nodejs-video-intelligence/pull/419

Sample tests are failing on master, un-related to any changes we seem to be making:
```
analyze.js labels-file <filePath>

Labels objects in a video stored locally using the Cloud Video Intelligence API.

Options:
  --version  Show version number                                                                               [boolean]
  --help     Show help                                                                                         [boolean]

Error: 3 INVALID_ARGUMENT: Request contains an invalid argument.
    at Object.callErrorFromStatus (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
    at Object.onReceiveStatus (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.handleTrailers (/Users/beckwith/Code/nodejs-video-intelligence/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:256:14)
    at ClientHttp2Stream.emit (events.js:315:20)
    at emit (internal/http2/core.js:289:8) {
  code: 3,
  details: 'Request contains an invalid argument.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

This point to one of:
- a dependency (grpc, gax) did something sketch in a patch/feature release
- the backend started acting up

Either way, something we should investigate ASAP because it looks bad.

**Comment by nnegrey** [comment]
I'll update the test to use a new file, filed a bug about the issue. Started happening across all languages where the file suddenly became invalid.

**Comment by JustinBeckwith** [comment]
Oh weird.  Should we add the file to source control, and have it upload itself to the bucket before testing?  Or is there a way we can lock down these resources to prevent that kind of thing from happening?

**Comment by nnegrey** [comment]
Well the file in question hasn't been touched in 3 years. So they must've made a change on the backend. 

https://github.com/googleapis/nodejs-video-intelligence/blob/master/samples/resources/cat.mp4
