### ISSUE TITLE
The caller does not have permission

### ISSUE THREAD

**Issue by nikhilmufc7** [googleapis/nodejs-video-intelligence#451]
Hi there, I am using google cloud vision api for filtering inappropriate videos in my app and I have followed all the steps mentioned in readme as well as in the official docs [here](https://cloud.google.com/video-intelligence/docs/analyze-safesearch#video_analyze_explicit_content-nodejs)

I am getting The caller does not have permission error every time.

I am running it using nodejs
I have owner permission to the project
I have created service account and environment variables to get access to the project on gcp following the docs [here](https://cloud.google.com/docs/authentication/getting-started)
I also tested the variables by getting the list of buckets from gcp and it worked fine for that.

This is the response that i am getting

```
➜  npmtest git:(master) ✗ node index.js safe-search gs://lets_tok_test/file_example_MP4_480_1_5MG.mp4
index.js safe-search <gcsUri>

Detects explicit content in a video stored in Google Cloud Storage.

Options:
  --version  Show version number                                                                               [boolean]
  --help     Show help                                                                                         [boolean]

Error: 7 PERMISSION_DENIED: The caller does not have permission
    at Object.callErrorFromStatus (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (/Users/nikhilsingh/Desktop/npmtest/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)
    at ClientHttp2Stream.emit (events.js:315:20)
    at emit (internal/http2/core.js:289:8) {
  code: 7,
  details: 'The caller does not have permission',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

This is my code that I am running 

```
'use strict'

async function analyzeSafeSearch (gcsUri) {
  // [START video_analyze_explicit_content]
  // Imports the Google Cloud Video Intelligence library
  const video = require('@google-cloud/video-intelligence').v1

  // Creates a client
  const client = new video.VideoIntelligenceServiceClient()

  /**
   * TODO(developer): Uncomment the following line before running the sample.
   */
  gcsUri = 'gs://lets_tok_test/file_example_MP4_480_1_5MG.mp4'

  const request = {
    inputUri: gcsUri,
    features: ['EXPLICIT_CONTENT_DETECTION']
  }

  // Human-readable likelihoods
  const likelihoods = [
    'UNKNOWN',
    'VERY_UNLIKELY',
    'UNLIKELY',
    'POSSIBLE',
    'LIKELY',
    'VERY_LIKELY'
  ]

  // Detects unsafe content
  const [opertaion] = await client.annotateVideo(request)
  console.log('Waiting for operation to complete...')
  const [operationResult] = await opertaion.promise()
  // Gets unsafe content
  const explicitContentResults =
    operationResult.annotationResults[0].explicitAnnotation
  console.log('Explicit annotation results:')
  explicitContentResults.frames.forEach(result => {
    if (result.timeOffset === undefined) {
      result.timeOffset = {}
    }
    if (result.timeOffset.seconds === undefined) {
      result.timeOffset.seconds = 0
    }
    if (result.timeOffset.nanos === undefined) {
      result.timeOffset.nanos = 0
    }
    console.log(
      `\tTime: ${result.timeOffset.seconds}` +
        `.${(result.timeOffset.nanos / 1e6).toFixed(0)}s`
    )
    console.log(
      `\t\tPornography likelihood: ${likelihoods[result.pornographyLikelihood]}`
    )
  })
  // [END video_analyze_explicit_content]
}

async function main () {
  require('yargs')
    .demand(1)
    .command(
      'safe-search <gcsUri>',
      'Detects explicit content in a video stored in Google Cloud Storage.',
      {},
      opts => analyzeSafeSearch(opts.gcsUri)
    )
    .example(
      'node $0 safe-search gs://lets_tok_test/file_example_MP4_480_1_5MG.mp4'
    )
    .wrap(120)
    .recommendCommands()
    .epilogue(
      'For more information, see https://cloud.google.com/video-intelligence/docs'
    )
    .help()
    .strict().argv
}

main().catch(console.error)
```

I have followed all the steps mentioned in readme but I can't figure what I am missing or doing wrong!

**Comment by munkhuushmgl** [comment]
@nikhilmufc7 Did you enable video intelligence API on your console?

**Comment by munkhuushmgl** [comment]
Or other case will be: your service account does not have enough permission to call Video int API.
Could you also make sure your SA have permission to Video Int API?

**Comment by nikhilmufc7** [comment]
Thanks @munkhuushmgl  it was a issue with environment variables
