### ISSUE TITLE
Cannot catch RESOURCE_EXHAUSTED Quota exceeded error 

### ISSUE THREAD

**Issue by hellovietduc** [googleapis/nodejs-video-intelligence#523]
I'm trying out the Video Intelligence API, the quota is the default 60 reqs/min and 180 mins backend time. When I send more than the limit, I get this error:

```
Error: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:xxx'.
    at Object.callErrorFromStatus (/xxx/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/xxx/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/xxx/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/xxx/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /xxx/node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

But the weird thing is **I can't catch it**.

#### Environment details

  - OS: MacOS Big Sur 11.2.3
  - Node.js version: v14.15.1
  - npm version: 6.14.8
  - `@google-cloud/video-intelligence` version: 3.3.0

#### Steps to reproduce

```typescript	

try {
	const [operation] = await client.annotateVideo(request)
	operation.on('error', (err) => {
		// failed to catch here
	})
	const [operationResult] = await operation.promise()
	// ...
} catch (err) {
	// also failed to catch here
}
```

**Comment by hellovietduc** [comment]
Update: the error has a `note` field: `Exception occurred in retry method that was not classified as transient`
